# Generated by Django 4.2.4 on 2023-09-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='decription',
            new_name='description',
        ),
    ]
