# Generated by Django 4.2.4 on 2023-09-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advert', '0003_alter_advert_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advert',
            table='advert',
        ),
    ]
