# Generated by Django 4.2.4 on 2023-09-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advert', '0004_alter_advert_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
